[package]
name = "create-data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24.8", default-features = false, features = ["png"] }
oxipng = "9.0.0"
resvg = "0.37.0"
