[package]
name = "shogi-img"
version = "0.7.0"
authors = ["sugyan <sugi1982+github@gmail.com>"]
edition = "2024"
description = "library for generating images that visualize the position in Shogi (Japanese chess)"
documentation = "https://docs.rs/shogi-img"
readme = "../README.md"
repository = "https://github.com/sugyan/shogi-img"
license = "MIT"
keywords = ["shogi"]

[dependencies]
ab_glyph = "0.2.23"
image = { version = "0.25.6", default-features = false, features = ["png"] }
shogi_core = "0.1.5"
